logging:
    advanced:
        enabled: True
        config:
            version: 1
            disable_existing_loggers: False
            formatters:
                console:
                    format: '[%(asctime)s] %(levelname)s - %(message)s'
                dev:
                    format: '[%(asctime)s] {{%(filename)s:%(lineno)d}} %(levelname)s - %(message)s'
                prediction:
                    (): pythonjsonlogger.jsonlogger.JsonFormatter
                feedback:
                    (): pythonjsonlogger.jsonlogger.JsonFormatter
            handlers:
                console:
                    level: INFO
                    formatter: console
                    class: logging.StreamHandler
                    stream: ext://sys.stdout
                prediction:
                    class: logging.StreamHandler
                    formatter: prediction
                    level: INFO
                    stream: ext://sys.stdout
            loggers:
                bentoml:
                    handlers: [console]
                    level: INFO
                    propagate: False
                bentoml.prediction:
                    handlers: [prediction]
                    level: INFO
                    propagate: False
