FROM python:3.8.8-slim-buster

RUN pip install pip --upgrade \
    && pip install mlflow>=1.0 \
    && pip install numpy \
    && pip install pandas \
    && pip install scikit-learn
    && pip install google-cloud-storage
