name: Bump version

on:
  push:
    branches:
      - develop

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.SOCAR_DE_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.SOCAR_DE_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
          branch: develop
      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        with:
          body_path: body.md
          tag_name: ${{ env.REVISION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
