name: "Docker Build Push"
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: streamlit-meta
        uses: docker/metadata-action@v3
        with:
          images: lmj3502/streamlit
          tags: |
            type=pep440,pattern={{raw}}
      - name: Login to docker_hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: pwd
      - run: ls -a
      - uses: actions/checkout@v2
      - run: ls -a
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./frontend/Dockerfile
          tags: ${{ steps.streamlit-meta.outputs.tags }}
